name: Auto release
description: Auto release
author: TDesign
inputs:
  tag:
    description: 指定 tag，否则读取 package.version
    required: false
outputs:
  changelog:
    description: 日志
runs:
  using: node20
  main: dist/index.js
