import { defineConfig } from 'tsdown'
import packageJson from './package.json' with { type: 'json' }

export default defineConfig({
  platform: 'node',
  shims: true,
  entry: ['src/index.ts'],
  deps: {
    alwaysBundle: [...Object.keys(packageJson.dependencies)],
    onlyBundle: [
      '@actions/core',
      '@actions/exec',
      '@actions/github',
      '@actions/http-client',
      '@actions/io',
      '@octokit/auth-token',
      '@octokit/core',
      '@octokit/endpoint',
      '@octokit/graphql',
      '@octokit/plugin-paginate-rest',
      '@octokit/plugin-rest-endpoint-methods',
      '@octokit/request',
      '@octokit/request-error',
      'agent-base',
      'asynckit',
      'bignumber.js',
      'before-after-hook',
      'call-bind-apply-helpers',
      'camelcase',
      'combined-stream',
      'debug',
      'delayed-stream',
      'dunder-proto',
      'es-define-property',
      'es-errors',
      'es-object-atoms',
      'es-set-tostringtag',
      'fast-content-type-parse',
      'fdir',
      'form-data',
      'function-bind',
      'get-intrinsic',
      'get-proto',
      'get-stream',
      'gopd',
      'has-symbols',
      'has-tostringtag',
      'hasown',
      'https-proxy-agent',
      'is-stream',
      'json-bigint',
      'marked',
      'math-intrinsics',
      'mime-db',
      'mime-types',
      'ms',
      'node-fetch',
      'picomatch',
      'tinyglobby',
      'is-stream',
      'json-bigint',
      'marked',
      'math-intrinsics',
      'mime-db',
      'mime-types',
      'ms',
      'node-fetch',
      'picomatch',
      'tinyglobby',
      'tr46',
      'tencentcloud-sdk-nodejs-common',
      'tencentcloud-sdk-nodejs-hunyuan',
      'tslib',
      'tunnel',
      'undici',
      'universal-user-agent',
      'uuid',
      'webidl-conversions',
      'whatwg-url',
      'yaml',
    ],
  },
})
