name: PR_COMMENT_CI

on:
  issue_comment:
    types: [created]

jobs:
  check-collaborator:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request }}
    steps:
       - uses: actions/checkout@v4
       - uses: actions/github-script@v7
         with:
          script: |
            let next_action = ''
            const fs = require('fs')
            const CODEOWNERS = fs.readFileSync('.github/CODEOWNERS', 'utf8')
            if (CODEOWNERS.includes(`@${context.payload.comment.user.login}`)) {
              console.log('Allowed')
              const body = context.payload.comment.body
              if (body.startsWith('/update-build')) {
                next_action='update-build'
              } 
            } else {
               core.warning('You are not collaborator');
            }
            core.info(`next_action: ${next_action}`)
            core.setOutput('next_action', next_action)

  update-build:
    needs: check-collaborator
    runs-on: ubuntu-latest
    if: ${{ needs.check-collaborator.outputs.next_action == 'update-build' }}
    steps:
      - uses: actions/checkout@v4
      - name: gh checkout pr
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: gh pr checkout ${{ github.event.issue.number }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - run: pnpm install
      - run: pnpm build
      - name: Commit build
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          git add .
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "chore: build"
          git push
