# 文件名建议统一为 tag-push.yml
# 应用 publish.yml 的 demo

name: TAG_PUSH

on: create

jobs:
  TAG_PUSH:
    runs-on: ubuntu-latest
    if: github.event.ref_type == 'tag'
    steps:
      - run: echo ${{ github.event.ref_type }}
